Asynchronous communication of message sending function
miwashun/ChatSpace pull request #12
Opened 2019-04-26 12:39 UTC by miwashun

# WHAT
- Ajax通信の実装
# WHY
- 画面がリロードせずに投稿できる
- テキストのみ/画像のみ/画像とテキスト、それぞれでエラーが出ずに投稿ができる
- 連続での投稿が可能（送信ごとにフォームをリセット）
- 投稿と同時に最下部までスクロールする
- 日時を表記

2019-04-26 12:52 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^
また、レビューを依頼する際には実装画面のレイアウトを確認しやすくするため、Gyazoなどで画面スクショを載せるといいでしょう^^

2019-04-26 12:52 UTC, i-date commented on app/assets/javascripts/message.js
> +    var MessageImage = (message.image) ? `<img class: 'form__mask__image' src="${message.image}">` : ""
MessageImageではなく、messageImageとしましょう。

2019-04-28 02:36 UTC, miwashun commented on app/assets/javascripts/message.js
> +    var MessageImage = (message.image) ? `<img class: 'form__mask__image' src="${message.image}">` : ""
分かりました。
ローワーキャメルケースに変更しました。

2019-04-28 02:45 UTC, yuki-uchida requested changes

2019-04-28 02:45 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
何のHTMLを作るのかもわかる名前だと良いです

2019-04-28 02:45 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataよりも具体的な名前にしましょう

2019-04-28 02:51 UTC, miwashun commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
メソッド名を変更しました。

2019-04-28 03:00 UTC, miwashun commented on app/assets/javascripts/message.js
> +    .done(function(data){
命名規則に従って引数名を変更しました。

2019-04-28 03:06 UTC, ghost approved these changes
LGTMです！

2019-04-28 03:07 UTC, miwashun commented
ありがとうございます！

2019-04-28 03:07 UTC, merged