Chat screen view
miwashun/ChatSpace pull request #2
Opened 2019-04-07 07:08 UTC by miwashun

# WHAT
ChatSpaceのチャット画面のビューを作成
# WHY
*BEM,haml,scssを使用
*リンク,formは仮置き
*リセットファイルはYUI3

2019-04-07 07:19 UTC, yuki-uchida requested changes

2019-04-07 07:19 UTC, yuki-uchida commented on app/assets/stylesheets/index.scss
> +    .messages {
BEMに沿ったクラス命名を行い、アンバサンドを活用した省略系で記述してください

2019-04-07 09:37 UTC, miwashun commented on app/assets/stylesheets/index.scss
> +    .messages {
BEMに修正しました

2019-04-07 09:48 UTC, hiroki5123 commented
ビュー画面のキャプチャをこちらに添付してください

2019-04-07 09:53 UTC, ghost requested changes

2019-04-07 09:53 UTC, hiroki5123 commented on app/assets/stylesheets/index.scss
> +                content: "\f03e";
これってなんですか？

2019-04-07 09:55 UTC, miwashun commented
<img width="1440" alt="スクリーンショット 2019-04-07 18 53 46" src="https://user-images.githubusercontent.com/47296444/55681877-94d47a80-5966-11e9-8ce9-2cc526e16b0a.png">
失礼いたしました。
確認のほどよろしくお願いします。

2019-04-08 02:39 UTC, miwashun commented on app/assets/stylesheets/index.scss
> +                content: "\f03e";
font-awesomeのcssが必要だと勘違いしていました。

2019-04-08 02:44 UTC, kuroko918 reviewed
READMEについて確認させていただきたいのですが、groupsテーブルについてしか描かれていないのですが、usersやmessagesやuserとgroupの中間テーブルについてはどうされていましたでしょうか？

2019-04-08 02:44 UTC, kuroko918 commented on app/views/layouts/mailer.html.haml
> +!!!
mailerは使用しないのでこのファイルは消しておいてください。

2019-04-08 02:44 UTC, kuroko918 commented on app/views/layouts/mailer.text.haml
> += yield
mailerは使用しないのでこのファイルは消しておいてください。

2019-04-08 02:44 UTC, kuroko918 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
不要なコメントは消しておいてください。

2019-04-08 02:56 UTC, miwashun commented on app/views/layouts/mailer.html.haml
> +!!!
mailer.html.hamlを削除しました。

2019-04-08 02:56 UTC, miwashun commented on app/views/layouts/mailer.text.haml
> += yield
mailer.text.hamlを削除しました。

2019-04-08 02:59 UTC, miwashun commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
不要なコメントを削除しました。

2019-04-08 05:42 UTC, miwashun commented
READMEが書き漏れていたので加筆しました。

2019-04-08 05:51 UTC, kuroko918 commented on README.md
> +|image|text|null: false, foreign_key: true|
foreign_keyは外部キーカラムにしか使用できないです。
それ以外のforeign_keyは消しておきましょう！

2019-04-08 06:31 UTC, miwashun commented on README.md
> +|image|text|null: false, foreign_key: true|
外部キーの設定を修正しました。

2019-04-08 06:54 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットはやめましょう。

2019-04-08 07:09 UTC, miwashun commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットを削除しました。

2019-04-08 07:19 UTC, kuroko918 commented
いいかとおと思います、LGTMです！

2019-04-08 07:20 UTC, miwashun commented
ありがとうございます！

2019-04-08 07:21 UTC, merged